"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.roles = exports.permissions = exports.platformModules = void 0;
exports.platformModules = [
    {
        key: 'platform',
        name: 'Superadmin',
        icon: 'shield',
        audience: 'PLATFORM',
        sortOrder: 10,
        submodules: [
            {
                key: 'organizations',
                name: 'Organizaciones',
                route: '/platform/organizaciones',
                permissionKey: 'platform.organizations.read',
                sortOrder: 10,
            },
            {
                key: 'global-users',
                name: 'Usuarios globales',
                route: '/platform/usuarios',
                permissionKey: 'platform.users.read',
                sortOrder: 20,
            },
            {
                key: 'roles',
                name: 'Roles base',
                route: '/platform/roles',
                permissionKey: 'platform.roles.read',
                sortOrder: 30,
            },
            {
                key: 'permissions',
                name: 'Permisos maestros',
                route: '/platform/permisos',
                permissionKey: 'platform.permissions.read',
                sortOrder: 40,
            },
            {
                key: 'modules',
                name: 'Modulos del sistema',
                route: '/platform/modulos',
                permissionKey: 'platform.modules.read',
                sortOrder: 50,
            },
            {
                key: 'activity',
                name: 'Actividad global',
                route: '/platform/actividad',
                permissionKey: 'platform.activity.read',
                sortOrder: 60,
            },
        ],
    },
    {
        key: 'dashboard',
        name: 'Inicio',
        icon: 'layout-dashboard',
        audience: 'ORGANIZATION',
        sortOrder: 20,
        submodules: [
            {
                key: 'home',
                name: 'Panel principal',
                route: '/dashboard',
                permissionKey: 'dashboard.read',
                sortOrder: 10,
            },
        ],
    },
    {
        key: 'settings',
        name: 'Configuracion',
        icon: 'settings',
        audience: 'ORGANIZATION',
        sortOrder: 30,
        submodules: [
            {
                key: 'organization',
                name: 'Empresa',
                route: '/configuracion/empresa',
                permissionKey: 'settings.organization.read',
                sortOrder: 10,
            },
            {
                key: 'branches',
                name: 'Sucursales',
                route: '/configuracion/sucursales',
                permissionKey: 'settings.branches.read',
                sortOrder: 20,
            },
            {
                key: 'users',
                name: 'Usuarios',
                route: '/configuracion/usuarios',
                permissionKey: 'settings.users.read',
                sortOrder: 30,
            },
            {
                key: 'roles',
                name: 'Roles',
                route: '/configuracion/roles',
                permissionKey: 'settings.roles.read',
                sortOrder: 40,
            },
            {
                key: 'parameters',
                name: 'Parametros',
                route: '/configuracion/parametros',
                permissionKey: 'settings.parameters.read',
                sortOrder: 50,
            },
        ],
    },
    {
        key: 'rrhh',
        name: 'Recursos humanos',
        icon: 'users',
        audience: 'ORGANIZATION',
        sortOrder: 40,
        submodules: [
            {
                key: 'collaborators',
                name: 'Colaboradores',
                route: '/rrhh/colaboradores',
                permissionKey: 'rrhh.collaborators.read',
                sortOrder: 10,
            },
            {
                key: 'attendance',
                name: 'Asistencia',
                route: '/rrhh/asistencia',
                permissionKey: 'rrhh.attendance.read',
                sortOrder: 20,
            },
            {
                key: 'payroll',
                name: 'Boletas de pago',
                route: '/rrhh/boletas-pago',
                permissionKey: 'rrhh.payroll.read',
                sortOrder: 30,
            },
        ],
    },
    {
        key: 'sales',
        name: 'Ventas',
        icon: 'shopping-bag',
        audience: 'ORGANIZATION',
        sortOrder: 50,
        submodules: [
            {
                key: 'customers',
                name: 'Clientes',
                route: '/ventas/clientes',
                permissionKey: 'sales.customers.read',
                sortOrder: 10,
            },
            {
                key: 'quotes',
                name: 'Cotizaciones',
                route: '/ventas/cotizaciones',
                permissionKey: 'sales.quotes.read',
                sortOrder: 20,
            },
            {
                key: 'orders',
                name: 'Pedidos',
                route: '/ventas/pedidos',
                permissionKey: 'sales.orders.read',
                sortOrder: 30,
            },
            {
                key: 'pos',
                name: 'POS',
                route: '/ventas/pos',
                permissionKey: 'sales.pos.read',
                sortOrder: 40,
            },
        ],
    },
    {
        key: 'cash',
        name: 'Caja',
        icon: 'wallet',
        audience: 'ORGANIZATION',
        sortOrder: 60,
        submodules: [
            {
                key: 'openings',
                name: 'Apertura',
                route: '/caja/apertura',
                permissionKey: 'cash.openings.read',
                sortOrder: 10,
            },
            {
                key: 'movements',
                name: 'Movimientos',
                route: '/caja/movimientos',
                permissionKey: 'cash.movements.read',
                sortOrder: 20,
            },
            {
                key: 'closings',
                name: 'Cierre',
                route: '/caja/cierre',
                permissionKey: 'cash.closings.read',
                sortOrder: 30,
            },
        ],
    },
    {
        key: 'inventory',
        name: 'Inventario',
        icon: 'package',
        audience: 'ORGANIZATION',
        sortOrder: 70,
        submodules: [
            {
                key: 'products',
                name: 'Productos',
                route: '/inventario/productos',
                permissionKey: 'inventory.products.read',
                sortOrder: 10,
            },
            {
                key: 'categories',
                name: 'Categorias',
                route: '/inventario/categorias',
                permissionKey: 'inventory.categories.read',
                sortOrder: 20,
            },
            {
                key: 'stock',
                name: 'Stock',
                route: '/inventario/stock',
                permissionKey: 'inventory.stock.read',
                sortOrder: 30,
            },
            {
                key: 'adjustments',
                name: 'Ajustes',
                route: '/inventario/ajustes',
                permissionKey: 'inventory.adjustments.read',
                sortOrder: 40,
            },
        ],
    },
    {
        key: 'billing',
        name: 'Facturacion',
        icon: 'receipt',
        audience: 'ORGANIZATION',
        sortOrder: 80,
        submodules: [
            {
                key: 'documents',
                name: 'Documentos',
                route: '/facturacion/documentos',
                permissionKey: 'billing.documents.read',
                sortOrder: 10,
            },
            {
                key: 'series',
                name: 'Series',
                route: '/facturacion/series',
                permissionKey: 'billing.series.read',
                sortOrder: 20,
            },
            {
                key: 'providers',
                name: 'Integraciones',
                route: '/facturacion/integraciones',
                permissionKey: 'billing.providers.read',
                sortOrder: 30,
            },
        ],
    },
    {
        key: 'reports',
        name: 'Reportes',
        icon: 'bar-chart-3',
        audience: 'ORGANIZATION',
        sortOrder: 90,
        submodules: [
            {
                key: 'sales',
                name: 'Ventas',
                route: '/reportes/ventas',
                permissionKey: 'reports.sales.read',
                sortOrder: 10,
            },
            {
                key: 'cash',
                name: 'Caja',
                route: '/reportes/caja',
                permissionKey: 'reports.cash.read',
                sortOrder: 20,
            },
            {
                key: 'inventory',
                name: 'Inventario',
                route: '/reportes/inventario',
                permissionKey: 'reports.inventory.read',
                sortOrder: 30,
            },
            {
                key: 'customers',
                name: 'Clientes',
                route: '/reportes/clientes',
                permissionKey: 'reports.customers.read',
                sortOrder: 40,
            },
        ],
    },
    {
        key: 'operations',
        name: 'Operaciones',
        icon: 'truck',
        audience: 'ORGANIZATION',
        sortOrder: 100,
        submodules: [
            {
                key: 'manifests',
                name: 'Manifiestos',
                route: '/manifiestos',
                permissionKey: 'operations.manifests.read',
                sortOrder: 10,
            },
            {
                key: 'carriers',
                name: 'Transportistas',
                route: '/transportistas',
                permissionKey: 'operations.carriers.read',
                sortOrder: 20,
            },
            {
                key: 'routes',
                name: 'Rutas',
                route: '/operaciones/rutas',
                permissionKey: 'operations.routes.read',
                sortOrder: 30,
            },
        ],
    },
];
exports.permissions = [
    {
        key: 'platform.organizations.read',
        name: 'Ver organizaciones',
        description: 'Permite ver empresas cliente registradas en Kapos.',
        moduleKey: 'platform',
        submoduleKey: 'organizations',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.organizations.create',
        name: 'Crear organizaciones',
        description: 'Permite crear nuevas organizaciones cliente.',
        moduleKey: 'platform',
        submoduleKey: 'organizations',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.organizations.manage',
        name: 'Gestionar organizaciones',
        description: 'Permite editar, suspender o reactivar organizaciones.',
        moduleKey: 'platform',
        submoduleKey: 'organizations',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.users.read',
        name: 'Ver usuarios globales',
        description: 'Permite revisar identidades globales de la plataforma.',
        moduleKey: 'platform',
        submoduleKey: 'global-users',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.users.create',
        name: 'Crear usuarios globales',
        description: 'Permite registrar identidades globales manualmente.',
        moduleKey: 'platform',
        submoduleKey: 'global-users',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.users.manage',
        name: 'Gestionar usuarios globales',
        description: 'Permite editar identidad, estado y acceso de plataforma de usuarios globales.',
        moduleKey: 'platform',
        submoduleKey: 'global-users',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.memberships.read',
        name: 'Ver memberships',
        description: 'Permite revisar relaciones entre usuarios y organizaciones.',
        moduleKey: 'platform',
        submoduleKey: 'global-users',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.memberships.manage',
        name: 'Gestionar memberships',
        description: 'Permite vincular owners, admins o colaboradores a organizaciones.',
        moduleKey: 'platform',
        submoduleKey: 'global-users',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.roles.read',
        name: 'Ver roles base',
        description: 'Permite consultar roles maestros de plataforma y organizacion.',
        moduleKey: 'platform',
        submoduleKey: 'roles',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.roles.manage',
        name: 'Gestionar roles base',
        description: 'Permite editar plantillas maestras de roles.',
        moduleKey: 'platform',
        submoduleKey: 'roles',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.permissions.read',
        name: 'Ver permisos maestros',
        description: 'Permite consultar el catalogo de permisos base.',
        moduleKey: 'platform',
        submoduleKey: 'permissions',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.permissions.manage',
        name: 'Gestionar permisos maestros',
        description: 'Permite crear o ajustar permisos base del sistema.',
        moduleKey: 'platform',
        submoduleKey: 'permissions',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.modules.read',
        name: 'Ver modulos del sistema',
        description: 'Permite consultar modulos y submodulos sembrados en Kapos.',
        moduleKey: 'platform',
        submoduleKey: 'modules',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.modules.manage',
        name: 'Gestionar modulos del sistema',
        description: 'Permite crear o ajustar modulos y submodulos base.',
        moduleKey: 'platform',
        submoduleKey: 'modules',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'platform.activity.read',
        name: 'Ver actividad global',
        description: 'Permite consultar actividad global de clientes y accesos.',
        moduleKey: 'platform',
        submoduleKey: 'activity',
        scope: 'PLATFORM',
        audience: 'PLATFORM',
    },
    {
        key: 'dashboard.read',
        name: 'Ver dashboard',
        description: 'Permite ver el panel principal del ERP.',
        moduleKey: 'dashboard',
        submoduleKey: 'home',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.organization.read',
        name: 'Ver empresa',
        description: 'Permite consultar datos generales de la organizacion.',
        moduleKey: 'settings',
        submoduleKey: 'organization',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.organization.manage',
        name: 'Gestionar empresa',
        description: 'Permite editar datos base de la organizacion.',
        moduleKey: 'settings',
        submoduleKey: 'organization',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.branches.read',
        name: 'Ver sucursales',
        description: 'Permite revisar sucursales habilitadas.',
        moduleKey: 'settings',
        submoduleKey: 'branches',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.branches.manage',
        name: 'Gestionar sucursales',
        description: 'Permite crear o editar sucursales.',
        moduleKey: 'settings',
        submoduleKey: 'branches',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.users.read',
        name: 'Ver usuarios',
        description: 'Permite listar usuarios internos de la organizacion.',
        moduleKey: 'settings',
        submoduleKey: 'users',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.users.create',
        name: 'Crear usuarios',
        description: 'Permite crear cuentas internas.',
        moduleKey: 'settings',
        submoduleKey: 'users',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.users.assign_roles',
        name: 'Asignar roles',
        description: 'Permite asignar roles a memberships internas.',
        moduleKey: 'settings',
        submoduleKey: 'users',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.roles.read',
        name: 'Ver roles',
        description: 'Permite listar roles de la organizacion.',
        moduleKey: 'settings',
        submoduleKey: 'roles',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.roles.create',
        name: 'Crear roles',
        description: 'Permite crear roles internos.',
        moduleKey: 'settings',
        submoduleKey: 'roles',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.roles.manage_permissions',
        name: 'Gestionar permisos de roles',
        description: 'Permite definir permisos de roles internos.',
        moduleKey: 'settings',
        submoduleKey: 'roles',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.parameters.read',
        name: 'Ver parametros',
        description: 'Permite revisar parametros generales del ERP.',
        moduleKey: 'settings',
        submoduleKey: 'parameters',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'settings.parameters.manage',
        name: 'Gestionar parametros',
        description: 'Permite editar parametros globales del cliente.',
        moduleKey: 'settings',
        submoduleKey: 'parameters',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'rrhh.collaborators.read',
        name: 'Ver colaboradores',
        description: 'Permite listar colaboradores de la organizacion.',
        moduleKey: 'rrhh',
        submoduleKey: 'collaborators',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'rrhh.collaborators.create',
        name: 'Crear colaboradores',
        description: 'Permite registrar nuevos colaboradores.',
        moduleKey: 'rrhh',
        submoduleKey: 'collaborators',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'rrhh.collaborators.update',
        name: 'Editar colaboradores',
        description: 'Permite actualizar datos de colaboradores.',
        moduleKey: 'rrhh',
        submoduleKey: 'collaborators',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'rrhh.attendance.read',
        name: 'Ver asistencia',
        description: 'Permite revisar asistencia por sede.',
        moduleKey: 'rrhh',
        submoduleKey: 'attendance',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'rrhh.payroll.read',
        name: 'Ver boletas',
        description: 'Permite revisar boletas y planillas.',
        moduleKey: 'rrhh',
        submoduleKey: 'payroll',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'sales.customers.read',
        name: 'Ver clientes',
        description: 'Permite consultar clientes comerciales.',
        moduleKey: 'sales',
        submoduleKey: 'customers',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'sales.customers.create',
        name: 'Crear clientes',
        description: 'Permite registrar nuevos clientes.',
        moduleKey: 'sales',
        submoduleKey: 'customers',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'sales.quotes.read',
        name: 'Ver cotizaciones',
        description: 'Permite revisar cotizaciones.',
        moduleKey: 'sales',
        submoduleKey: 'quotes',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'sales.quotes.create',
        name: 'Crear cotizaciones',
        description: 'Permite emitir cotizaciones.',
        moduleKey: 'sales',
        submoduleKey: 'quotes',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'sales.orders.read',
        name: 'Ver pedidos',
        description: 'Permite consultar pedidos.',
        moduleKey: 'sales',
        submoduleKey: 'orders',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'sales.orders.create',
        name: 'Crear pedidos',
        description: 'Permite registrar pedidos.',
        moduleKey: 'sales',
        submoduleKey: 'orders',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'sales.pos.read',
        name: 'Ver POS',
        description: 'Permite usar o revisar el punto de venta.',
        moduleKey: 'sales',
        submoduleKey: 'pos',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'cash.openings.read',
        name: 'Ver aperturas de caja',
        description: 'Permite consultar aperturas de caja.',
        moduleKey: 'cash',
        submoduleKey: 'openings',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'cash.openings.manage',
        name: 'Gestionar aperturas de caja',
        description: 'Permite abrir caja o ajustar una apertura.',
        moduleKey: 'cash',
        submoduleKey: 'openings',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'cash.movements.read',
        name: 'Ver movimientos de caja',
        description: 'Permite consultar ingresos y salidas de caja.',
        moduleKey: 'cash',
        submoduleKey: 'movements',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'cash.movements.manage',
        name: 'Gestionar movimientos de caja',
        description: 'Permite registrar ingresos y egresos de caja.',
        moduleKey: 'cash',
        submoduleKey: 'movements',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'cash.closings.read',
        name: 'Ver cierres de caja',
        description: 'Permite consultar cierres de caja.',
        moduleKey: 'cash',
        submoduleKey: 'closings',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'cash.closings.manage',
        name: 'Gestionar cierres de caja',
        description: 'Permite cerrar caja y validar diferencias.',
        moduleKey: 'cash',
        submoduleKey: 'closings',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'inventory.products.read',
        name: 'Ver productos',
        description: 'Permite listar productos e insumos.',
        moduleKey: 'inventory',
        submoduleKey: 'products',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'inventory.products.manage',
        name: 'Gestionar productos',
        description: 'Permite crear o editar productos e insumos.',
        moduleKey: 'inventory',
        submoduleKey: 'products',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'inventory.categories.read',
        name: 'Ver categorias',
        description: 'Permite revisar categorias de inventario.',
        moduleKey: 'inventory',
        submoduleKey: 'categories',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'inventory.categories.manage',
        name: 'Gestionar categorias',
        description: 'Permite crear o editar categorias.',
        moduleKey: 'inventory',
        submoduleKey: 'categories',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'inventory.stock.read',
        name: 'Ver stock',
        description: 'Permite consultar stock por organizacion o sede.',
        moduleKey: 'inventory',
        submoduleKey: 'stock',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'inventory.adjustments.read',
        name: 'Ver ajustes de stock',
        description: 'Permite consultar ajustes de stock.',
        moduleKey: 'inventory',
        submoduleKey: 'adjustments',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'inventory.adjustments.manage',
        name: 'Gestionar ajustes de stock',
        description: 'Permite crear ajustes de inventario.',
        moduleKey: 'inventory',
        submoduleKey: 'adjustments',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'billing.documents.read',
        name: 'Ver documentos',
        description: 'Permite revisar documentos emitidos.',
        moduleKey: 'billing',
        submoduleKey: 'documents',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'billing.documents.manage',
        name: 'Gestionar documentos',
        description: 'Permite emitir o reenviar documentos.',
        moduleKey: 'billing',
        submoduleKey: 'documents',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'billing.series.read',
        name: 'Ver series',
        description: 'Permite revisar series y correlativos.',
        moduleKey: 'billing',
        submoduleKey: 'series',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'billing.series.manage',
        name: 'Gestionar series',
        description: 'Permite editar series y correlativos.',
        moduleKey: 'billing',
        submoduleKey: 'series',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'billing.providers.read',
        name: 'Ver integraciones de facturacion',
        description: 'Permite revisar integraciones de facturacion.',
        moduleKey: 'billing',
        submoduleKey: 'providers',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'reports.sales.read',
        name: 'Ver reportes de ventas',
        description: 'Permite consultar reportes de ventas.',
        moduleKey: 'reports',
        submoduleKey: 'sales',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'reports.cash.read',
        name: 'Ver reportes de caja',
        description: 'Permite consultar reportes de caja.',
        moduleKey: 'reports',
        submoduleKey: 'cash',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'reports.inventory.read',
        name: 'Ver reportes de inventario',
        description: 'Permite consultar reportes de inventario.',
        moduleKey: 'reports',
        submoduleKey: 'inventory',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'reports.customers.read',
        name: 'Ver reportes de clientes',
        description: 'Permite consultar reportes de clientes.',
        moduleKey: 'reports',
        submoduleKey: 'customers',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'operations.manifests.read',
        name: 'Ver manifiestos',
        description: 'Permite consultar manifiestos operativos.',
        moduleKey: 'operations',
        submoduleKey: 'manifests',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
    {
        key: 'operations.carriers.read',
        name: 'Ver transportistas',
        description: 'Permite listar transportistas.',
        moduleKey: 'operations',
        submoduleKey: 'carriers',
        scope: 'ORGANIZATION',
        audience: 'ORGANIZATION',
    },
    {
        key: 'operations.routes.read',
        name: 'Ver rutas',
        description: 'Permite consultar rutas operativas.',
        moduleKey: 'operations',
        submoduleKey: 'routes',
        scope: 'BRANCH',
        audience: 'ORGANIZATION',
    },
];
exports.roles = [
    {
        context: 'PLATFORM',
        scopeKey: 'platform:platform.super_admin',
        key: 'platform.super_admin',
        name: 'Superadmin de plataforma',
        description: 'Acceso completo a clientes, catalogos base y actividad global de Kapos.',
        isSystem: true,
        permissionKeys: exports.permissions
            .filter((permission) => permission.audience === 'PLATFORM')
            .map((permission) => permission.key),
    },
    {
        context: 'PLATFORM',
        scopeKey: 'platform:platform.assistant',
        key: 'platform.assistant',
        name: 'Asistente de plataforma',
        description: 'Apoya al superadmin con lectura operativa y tareas delegadas sin control absoluto de Kapos.',
        isSystem: true,
        permissionKeys: [
            'platform.organizations.read',
            'platform.users.read',
            'platform.memberships.read',
            'platform.roles.read',
            'platform.permissions.read',
            'platform.modules.read',
            'platform.activity.read',
        ],
    },
    {
        context: 'ORGANIZATION',
        scopeKey: 'system:organization.owner',
        key: 'organization.owner',
        name: 'Owner de organizacion',
        description: 'Maximo responsable del cliente dentro de Kapos.',
        isSystem: true,
        permissionKeys: exports.permissions
            .filter((permission) => permission.audience === 'ORGANIZATION')
            .map((permission) => permission.key),
    },
    {
        context: 'ORGANIZATION',
        scopeKey: 'system:organization.admin',
        key: 'organization.admin',
        name: 'Administrador de organizacion',
        description: 'Gestiona usuarios internos, configuracion y operacion general.',
        isSystem: true,
        permissionKeys: [
            'dashboard.read',
            'settings.organization.read',
            'settings.organization.manage',
            'settings.branches.read',
            'settings.users.read',
            'settings.users.create',
            'settings.users.assign_roles',
            'settings.roles.read',
            'settings.roles.create',
            'settings.parameters.read',
            'settings.parameters.manage',
            'rrhh.collaborators.read',
            'rrhh.collaborators.create',
            'rrhh.collaborators.update',
            'rrhh.attendance.read',
            'rrhh.payroll.read',
            'sales.customers.read',
            'sales.customers.create',
            'sales.quotes.read',
            'sales.quotes.create',
            'sales.orders.read',
            'sales.orders.create',
            'sales.pos.read',
            'cash.openings.read',
            'cash.movements.read',
            'cash.closings.read',
            'inventory.products.read',
            'inventory.categories.read',
            'inventory.stock.read',
            'billing.documents.read',
            'billing.series.read',
            'reports.sales.read',
            'reports.cash.read',
            'reports.inventory.read',
            'reports.customers.read',
            'operations.manifests.read',
            'operations.carriers.read',
            'operations.routes.read',
        ],
    },
    {
        context: 'ORGANIZATION',
        scopeKey: 'system:organization.supervisor',
        key: 'organization.supervisor',
        name: 'Supervisor',
        description: 'Controla operacion diaria y revisa resultados sin dominio total del sistema.',
        isSystem: true,
        permissionKeys: [
            'dashboard.read',
            'rrhh.collaborators.read',
            'rrhh.attendance.read',
            'sales.customers.read',
            'sales.quotes.read',
            'sales.orders.read',
            'sales.orders.create',
            'sales.pos.read',
            'cash.openings.read',
            'cash.movements.read',
            'cash.closings.read',
            'inventory.products.read',
            'inventory.categories.read',
            'inventory.stock.read',
            'reports.sales.read',
            'reports.cash.read',
            'operations.manifests.read',
            'operations.routes.read',
        ],
    },
    {
        context: 'ORGANIZATION',
        scopeKey: 'system:organization.cashier',
        key: 'organization.cashier',
        name: 'Cajero u operador base',
        description: 'Rol operativo para caja, pedidos y POS con alcance limitado.',
        isSystem: true,
        permissionKeys: [
            'dashboard.read',
            'sales.customers.read',
            'sales.orders.read',
            'sales.orders.create',
            'sales.pos.read',
            'cash.openings.read',
            'cash.movements.read',
            'cash.closings.read',
        ],
    },
];
